title: Lemonbrush
author: Lemonbrush
email: aa_rubtsov@mail.ru
description: >
    Hi, I am Alex. Software engineer and indie game developer based in Russia. It is my dev log archive. Here you can see what I currently do 
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 10
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  disqus:
    shortname: lemonbrush.github.io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://www.youtube.com/channel/UCtzr1r4OS5p6ZvT2R3umd3Q
      icon: youtube
      color: red
    - url: https://www.behance.net/lemonbrush?locale=it_IT
      icon: behance-square
      color: blue
    - url: https://t.me/+KXg8D_VXYrZiZWQy
      icon: telegram
      color: blue
    - url: https://discord.gg/Z4hPB8Bx
      icon: discord
      color: purple
    - url: https://lemonbrush.itch.io
      icon: itch-io
      color: red
    - url: https://github.com/Lemonbrush
      icon: github-square
      color: orange

  # wether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  avatar_source: github
  github_username: Lemonbrush
  #avatar_source: local
  #avatar_path: /assets/avatar.png

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll/tagging
