site: Lemonbrush
url: #yoururl
title: Lemonbrush
description: Personal dev log archive
twitter:
  username: #yourusername
  card: summary
  creator: #yourusername
author:
  twitter: #yourusername
  name: Lemonbrush
  avatar: https://avatars.githubusercontent.com/u/14632982?s=400&u=dbb61a1ad299f9996d988b2025d9be12fb618bad&v=4
  email: aa_rubtsov@mail.ru
  url: #yoururl
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
